"""Enumeration of tableau node types and their properties."""

from __future__ import annotations

from enum import Enum


class NodeType(Enum):
    """Classifies a tableau node and controls merge / blocking behaviour.

    Each variant carries three attributes that mirror the Java constants:

    * ``merge_precedence`` -- lower values take priority when merging
      (the node with the *lower* precedence absorbs the other).
    * ``is_ni_target`` -- whether the node is a valid target for nominal
      introduction merging.
    * ``is_abstract`` -- whether the node can hold abstract concept
      assertions (``True`` for all node types except ``CONCRETE_NODE``).

    Variants:
        NAMED_NODE: An individual explicitly named in the input ontology.
        NI_NODE: A nominal-introduction node (not directly named).
        ROOT_CONSTANT_NODE: A root-level constant (used for datatype reasoning).
        TREE_NODE: A node generated by an existential expansion.
        GRAPH_NODE: A node belonging to a description graph.
        CONCRETE_NODE: A concrete (datatype) node.
    """

    NAMED_NODE = (0, False, True)
    NI_NODE = (1, False, True)
    ROOT_CONSTANT_NODE = (1, False, False)
    TREE_NODE = (2, True, True)
    GRAPH_NODE = (2, True, True)
    CONCRETE_NODE = (2, False, False)

    def __init__(
        self,
        merge_precedence: int,
        is_ni_target: bool,
        is_abstract: bool,
    ) -> None:
        self._merge_precedence = merge_precedence
        self._is_ni_target = is_ni_target
        self._is_abstract = is_abstract

    # -- Accessors -----------------------------------------------------

    @property
    def merge_precedence(self) -> int:
        """Return the merge precedence (lower = absorbs first)."""
        return self._merge_precedence

    @property
    def is_ni_target(self) -> bool:
        """Return ``True`` if this node type is a target for nominal introduction."""
        return self._is_ni_target

    @property
    def is_abstract(self) -> bool:
        """Return ``True`` if the node can hold concept (not datatype) assertions."""
        return self._is_abstract
